# Generated by Django 3.0 on 2020-10-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategorymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.CategoryModel'),
        ),
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='category',
            field=models.ManyToManyField(null=True, related_name='sub_category', to='products.CategoryModel'),
        ),
    ]
