# Generated by Django 3.0 on 2020-10-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201022_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('name',), 'verbose_name': 'label', 'verbose_name_plural': 'labels'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
