# Generated by Django 3.0 on 2020-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201022_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products-images/%Y/%m/%d'),
        ),
    ]
