# Generated by Django 3.0 on 2020-10-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201022_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(null=True, related_name='labels', to='products.Label'),
        ),
    ]
